In [1]:
import numpy as np

# A vector representing a 4-dimensional word embedding
# Dimensions might represent abstract features: [animacy, royalty, gender, size]
king = np.array([0.9, 0.8, 0.9, 0.7])
queen = np.array([0.9, 0.8, 0.1, 0.6])
apple = np.array([0.1, 0.0, 0.5, 0.3])

print("King vector shape:", king.shape)
print("Queen vector:", queen)


King vector shape: (4,)
Queen vector: [0.9 0.8 0.1 0.6]


In [2]:
# Difference vector (isolating feature directions)
gender_direction = king - queen
print("Gender delta vector:", gender_direction)


Gender delta vector: [0.  0.  0.8 0.1]


In [3]:
# Compute dot product between king and queen vs king and apple
sim_king_queen = np.dot(king, queen)
sim_king_apple = np.dot(king, apple)

print(f"Alignment (King · Queen): {sim_king_queen:.4f}")
print(f"Alignment (King · Apple): {sim_king_apple:.4f}")

Alignment (King · Queen): 1.9600
Alignment (King · Apple): 0.7500


In [4]:
def cosine_similarity(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

print(f"Cosine Similarity (King, Queen): {cosine_similarity(king, queen):.4f}")
print(f"Cosine Similarity (King, Apple): {cosine_similarity(king, apple):.4f}")


Cosine Similarity (King, Queen): 0.8761
Cosine Similarity (King, Apple): 0.7645


In [5]:
# Input token vector (dimension: 4)
x = np.array([0.5, -0.2, 0.1, 0.9])

# Weight matrix W (output_dim: 3, input_dim: 4)
W = np.array([
    [0.1, 0.2, -0.1, 0.4],
    [-0.5, 0.3, 0.8, -0.2],
    [0.0, 0.9, 0.1, 0.5]
])

# Bias vector (dimension: 3)
b = np.array([0.1, -0.1, 0.0])

# Forward pass of a single linear layer
output = np.matmul(W, x) + b

print("Input shape: ", x.shape)
print("Weight shape:", W.shape)
print("Output shape:", output.shape)
print("Transformed output vector:\n", output)

Input shape:  (4,)
Weight shape: (3, 4)
Output shape: (3,)
Transformed output vector:
 [ 0.46 -0.51  0.28]


In [6]:
# Batch of 2 tokens (Sequence length = 2, Feature dim = 4)
X_batch = np.array([
    [0.5, -0.2, 0.1, 0.9],
    [0.8, 0.1, -0.4, 0.2]
])

# Matrix multiplication across all tokens in parallel
batch_output = np.matmul(X_batch, W.T)

print("Batch input shape: ", X_batch.shape)
print("Batch output shape:", batch_output.shape)
print("Batch output matrix:\n", batch_output)

Batch input shape:  (2, 4)
Batch output shape: (2, 3)
Batch output matrix:
 [[ 0.36 -0.41  0.28]
 [ 0.22 -0.73  0.15]]
