In [2]:
import numpy as np

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1.0 - s)

In [3]:
# 4 training samples: [Input 1, Input 2]
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Expected XOR outputs: 0 XOR 0 = 0, 0 XOR 1 = 1, 1 XOR 0 = 1, 1 XOR 1 = 0
y = np.array([[0], [1], [1], [0]])

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (4, 2)
y shape: (4, 1)


In [4]:
np.random.seed(42)

input_dim = 2
hidden_dim = 3
output_dim = 1

# Weights and biases
W1 = np.random.randn(input_dim, hidden_dim) * 0.1
b1 = np.zeros((1, hidden_dim))

W2 = np.random.randn(hidden_dim, output_dim) * 0.1
b2 = np.zeros((1, output_dim))

In [5]:
learning_rate = 0.5
epochs = 10000

for epoch in range(epochs):
    # --- FORWARD PASS ---
    z1 = np.dot(X, W1) + b1       # Linear step 1
    a1 = sigmoid(z1)              # Hidden activation
    
    z2 = np.dot(a1, W2) + b2      # Linear step 2
    y_pred = sigmoid(z2)          # Output prediction
    
    # Loss: Mean Squared Error (MSE)
    loss = np.mean((y_pred - y) ** 2)
    
    # --- BACKPROPAGATION (CALCULUS / CHAIN RULE) ---
    # Gradient of loss with respect to z2
    error_output = (y_pred - y) * sigmoid_derivative(z2)
    
    # Gradients for W2 and b2
    dW2 = np.dot(a1.T, error_output)
    db2 = np.sum(error_output, axis=0, keepdims=True)
    
    # Backpropagate error to hidden layer
    error_hidden = np.dot(error_output, W2.T) * sigmoid_derivative(z1)
    
    # Gradients for W1 and b1
    dW1 = np.dot(X.T, error_hidden)
    db1 = np.sum(error_hidden, axis=0, keepdims=True)
    
    # --- GRADIENT DESCENT UPDATE ---
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    
    if (epoch + 1) % 2000 == 0:
        print(f"Epoch {epoch + 1:5d} | Loss: {loss:.6f}")

Epoch  2000 | Loss: 0.249998
Epoch  4000 | Loss: 0.249968
Epoch  6000 | Loss: 0.007321
Epoch  8000 | Loss: 0.001166
Epoch 10000 | Loss: 0.000599


In [6]:
print("\nTarget Outputs:\n", y)
print("\nModel Predictions (rounded to nearest integer):\n", np.round(y_pred))
print("\nRaw Probabilities:\n", y_pred)


Target Outputs:
 [[0]
 [1]
 [1]
 [0]]

Model Predictions (rounded to nearest integer):
 [[0.]
 [1.]
 [1.]
 [0.]]

Raw Probabilities:
 [[0.02821261]
 [0.97691964]
 [0.97692529]
 [0.02308731]]
