In [1]:
import torch

# Create a tensor and track its operations
x = torch.tensor(3.0, requires_grad=True)

# Define a mathematical function: y = 2x^3 + 5x
y = 2 * (x ** 3) + 5 * x

# Compute the derivative dy/dx using autograd
y.backward()

# Theoretical derivative: dy/dx = 6x^2 + 5 -> at x=3: 6(9) + 5 = 59
print(f"Value of y: {y.item()}")
print(f"Computed gradient dy/dx at x=3: {x.grad.item()}")

Value of y: 69.0
Computed gradient dy/dx at x=3: 59.0


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# Prepare data as PyTorch Tensors
X = torch.tensor([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]
], dtype=torch.float32)

y = torch.tensor([
    [0.0],
    [1.0],
    [1.0],
    [0.0]
], dtype=torch.float32)

# Define the 2-layer Neural Network architecture
class XORNet(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=3, output_dim=1):
        super(XORNet, self).__init__()
        self.layer1 = nn.Linear(input_dim, hidden_dim)
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(hidden_dim, output_dim)
        self.sigmoid2 = nn.Sigmoid()
        
    def forward(self, x):
        out = self.layer1(x)
        out = self.sigmoid1(out)
        out = self.layer2(out)
        out = self.sigmoid2(out)
        return out

model = XORNet()
print(model)

XORNet(
  (layer1): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid2): Sigmoid()
)


In [3]:
# Binary Cross-Entropy Loss and Adam Optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.05)

epochs = 2000

for epoch in range(epochs):
    # 1. Reset gradients from previous step
    optimizer.zero_grad()
    
    # 2. Forward pass
    predictions = model(X)
    
    # 3. Compute loss
    loss = criterion(predictions, y)
    
    # 4. Backward pass (Autograd computes all dW and db)
    loss.backward()
    
    # 5. Gradient descent step (Updates all parameters)
    optimizer.step()
    
    if (epoch + 1) % 400 == 0:
        print(f"Epoch [{epoch + 1:4d}/{epochs}] | Loss: {loss.item():.6f}")

Epoch [ 400/2000] | Loss: 0.010047
Epoch [ 800/2000] | Loss: 0.003282
Epoch [1200/2000] | Loss: 0.001676
Epoch [1600/2000] | Loss: 0.001017
Epoch [2000/2000] | Loss: 0.000676


In [4]:
# Disable gradient computation for faster inference
with torch.no_grad():
    raw_outputs = model(X)
    rounded_preds = torch.round(raw_outputs)

print("\nActual Targets:\n", y.numpy())
print("\nModel Predictions:\n", rounded_preds.numpy())
print("\nRaw Probabilities:\n", raw_outputs.numpy())


Actual Targets:
 [[0.]
 [1.]
 [1.]
 [0.]]

Model Predictions:
 [[0.]
 [1.]
 [1.]
 [0.]]

Raw Probabilities:
 [[8.0349692e-04]
 [9.9873716e-01]
 [9.9995530e-01]
 [5.8970263e-04]]
